const actionTypes = {
    SET_PROFILE: 'SET_PROFILE',
    SET_SUMMARY_LIST: 'SET_SUMMARY_LIST',
    SET_SELECTED_TIMESHEET: 'SET_SELECTED_TIMESHEET',
    UPDATE_TIMESHEET: 'UPDATE_TIMESHEET'
}

export default actionTypes;